-- MySQL Script generated by MySQL Workbench
-- Sun Mar 15 22:12:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema safehouse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `safehouse` ;

-- -----------------------------------------------------
-- Schema safehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safehouse` DEFAULT CHARACTER SET utf8 ;
USE `safehouse` ;

-- -----------------------------------------------------
-- Table `safehouse`.`sensor_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`sensor_type` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`sensor_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safehouse`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`location` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`location` (
  `id` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safehouse`.`house`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`house` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`house` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `additional_security` TINYINT NOT NULL DEFAULT 0,
  `MAC_address` VARCHAR(12) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safehouse`.`valve`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`valve` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`valve` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `closed` TINYINT NOT NULL,
  `active` TINYINT NOT NULL,
  `house_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_valve_location1`
    FOREIGN KEY (`location`)
    REFERENCES `safehouse`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valve_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `safehouse`.`house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_valve_location1_idx` ON `safehouse`.`valve` (`location` ASC) VISIBLE;

CREATE INDEX `fk_valve_house1_idx` ON `safehouse`.`valve` (`house_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`sensor` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`sensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL,
  `location` INT NOT NULL,
  `valve` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `house_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sensor_sensor_type1`
    FOREIGN KEY (`type`)
    REFERENCES `safehouse`.`sensor_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_location1`
    FOREIGN KEY (`location`)
    REFERENCES `safehouse`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_valve1`
    FOREIGN KEY (`valve`)
    REFERENCES `safehouse`.`valve` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `safehouse`.`house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `safehouse`.`sensor` (`id` ASC) VISIBLE;

CREATE INDEX `fk_sensor_sensor_type1_idx` ON `safehouse`.`sensor` (`type` ASC) VISIBLE;

CREATE INDEX `fk_sensor_location1_idx` ON `safehouse`.`sensor` (`location` ASC) VISIBLE;

CREATE INDEX `fk_sensor_valve1_idx` ON `safehouse`.`sensor` (`valve` ASC) VISIBLE;

CREATE INDEX `fk_sensor_house1_idx` ON `safehouse`.`sensor` (`house_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`sensor_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`sensor_state` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`sensor_state` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sensor_id` INT NOT NULL,
  `active` TINYINT NOT NULL,
  `battery` INT NULL,
  `last_seen` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sensor_state_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `safehouse`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sensor_state_sensor1_idx` ON `safehouse`.`sensor_state` (`sensor_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `sensor_id_UNIQUE` ON `safehouse`.`sensor_state` (`sensor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`daily_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`daily_statistics` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`daily_statistics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sensor_id` INT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `day` DATE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_daily_statistics_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `safehouse`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_daily_statistics_sensor1_idx` ON `safehouse`.`daily_statistics` (`sensor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`user` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NULL,
  `active` INT NULL DEFAULT 1,
  `suspended` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `deleted` DATETIME NULL DEFAULT NULL,
  `last_updated` DATETIME NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `lock_count` INT NOT NULL DEFAULT 3,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `safehouse`.`user` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `safehouse`.`user` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`password` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`password` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_passwords_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `safehouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_passwords_users1_idx` ON `safehouse`.`password` (`user_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `user_id_UNIQUE` ON `safehouse`.`password` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`profile_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`profile_settings` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`profile_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `language` VARCHAR(3) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_profile_settings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `safehouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `user_id_UNIQUE` ON `safehouse`.`profile_settings` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_profile_settings_users1_idx` ON `safehouse`.`profile_settings` (`users_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`login_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`login_info` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`login_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `ip_address` VARCHAR(45) NULL,
  `device` VARCHAR(45) NULL,
  `browser` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_login_info_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `safehouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_login_info_users_idx` ON `safehouse`.`login_info` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`old_password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`old_password` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`old_password` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `changed_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_old_passwords_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `safehouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_old_passwords_users1_idx` ON `safehouse`.`old_password` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`monthly_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`monthly_statistics` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`monthly_statistics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sensor_id` INT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `mounth` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_monthly_statistics_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `safehouse`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_monthly_statistics_sensor1_idx` ON `safehouse`.`monthly_statistics` (`sensor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`hourly_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`hourly_statistics` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`hourly_statistics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sensor_id` INT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_hourly_statistics_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `safehouse`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_hourly_statistics_sensor1_idx` ON `safehouse`.`hourly_statistics` (`sensor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`user_has_house`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`user_has_house` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`user_has_house` (
  `user_id` INT NOT NULL,
  `house_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `house_id`),
  CONSTRAINT `fk_user_has_house_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `safehouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_house_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `safehouse`.`house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_has_house_house1_idx` ON `safehouse`.`user_has_house` (`house_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_house_user1_idx` ON `safehouse`.`user_has_house` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`permission` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`permission` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `house_id` INT NOT NULL,
  `close_valve` TINYINT NOT NULL DEFAULT 1,
  `add_sensor` TINYINT NOT NULL DEFAULT 1,
  `delete_sensor` TINYINT NOT NULL DEFAULT 1,
  `delete_user` TINYINT NOT NULL DEFAULT 1,
  `add_user` TINYINT NOT NULL DEFAULT 1,
  `edit_sensors` TINYINT NOT NULL DEFAULT 1,
  `edit_house_users` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_permission_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `safehouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permission_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `safehouse`.`house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_permission_user1_idx` ON `safehouse`.`permission` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_permission_house1_idx` ON `safehouse`.`permission` (`house_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`notification_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`notification_type` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`notification_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safehouse`.`telegram_bot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`telegram_bot` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`telegram_bot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `chat_id` INT NULL,
  `enabled` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_telegram_bot_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `safehouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telegram_bot_user1_idx` ON `safehouse`.`telegram_bot` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`bot_authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`bot_authentication` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`bot_authentication` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `code` VARCHAR(5) NOT NULL,
  `creation_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bot_authentication_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `safehouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bot_authentication_user1_idx` ON `safehouse`.`bot_authentication` (`user_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `code_UNIQUE` ON `safehouse`.`bot_authentication` (`code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`valve_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`valve_log` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`valve_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `sensor_id` INT NOT NULL,
  `valve_id` INT NOT NULL,
  `closed_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_valve_log_valve1`
    FOREIGN KEY (`valve_id`)
    REFERENCES `safehouse`.`valve` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valve_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `safehouse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valve_log_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `safehouse`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_valve_log_valve1_idx` ON `safehouse`.`valve_log` (`valve_id` ASC) VISIBLE;

CREATE INDEX `fk_valve_log_user1_idx` ON `safehouse`.`valve_log` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_valve_log_sensor1_idx` ON `safehouse`.`valve_log` (`sensor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `safehouse`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safehouse`.`notification` ;

CREATE TABLE IF NOT EXISTS `safehouse`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `house_id` INT NOT NULL,
  `notification_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_notification_house1`
    FOREIGN KEY (`house_id`)
    REFERENCES `safehouse`.`house` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_notification_type1`
    FOREIGN KEY (`notification_type_id`)
    REFERENCES `safehouse`.`notification_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_notification_house1_idx` ON `safehouse`.`notification` (`house_id` ASC) VISIBLE;

CREATE INDEX `fk_notification_notification_type1_idx` ON `safehouse`.`notification` (`notification_type_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
