# Generated by Django 2.2 on 2019-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(default='not given', max_length=254),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(default='not given', max_length=128),
        ),
    ]
